<script setup lang="ts">
import { Icon } from "@iconify/vue";
import type { Column, DesignerTab, Index, ForeignKey, CheckConstraint, TableSpec } from "../types";
const props = defineProps<{ tab: DesignerTab }>();
const emit = defineEmits<{ update: [patch: Partial<TableSpec>]; pane: [pane: DesignerTab["pane"]]; preview: []; apply: [] }>();
function setColumn(index: number, patch: Partial<Column>) { emit("update", { columns: props.tab.spec!.columns.map((column, row) => row === index ? { ...column, ...patch } : column) }); }
function addColumn() { const columns = props.tab.spec!.columns; emit("update", { columns: [...columns, { name: `field_${columns.length + 1}`, data_type: "VARCHAR(255)", nullable: true, default: null, extra: "", comment: "", generation: "" }] }); }
function removeColumn(index: number) { emit("update", { columns: props.tab.spec!.columns.filter((_, row) => row !== index) }); }
function setPrimary(name: string, checked: boolean) { const keys = props.tab.spec!.primary_key; emit("update", { primary_key: checked ? [...new Set([...keys, name])] : keys.filter(key => key !== name) }); }
function setIndex(index: number, patch: Partial<Index>) { emit("update", { indexes: props.tab.spec!.indexes.map((item, row) => row === index ? { ...item, ...patch } : item) }); }
function setForeign(index: number, patch: Partial<ForeignKey>) { emit("update", { foreign_keys: props.tab.spec!.foreign_keys.map((item, row) => row === index ? { ...item, ...patch } : item) }); }
function setCheck(index: number, patch: Partial<CheckConstraint>) { emit("update", { checks: props.tab.spec!.checks.map((item, row) => row === index ? { ...item, ...patch } : item) }); }
const panes = [{ id: "columns", label: "字段", icon: "lucide:columns-3" }, { id: "indexes", label: "索引", icon: "lucide:list-tree" }, { id: "foreign", label: "外键", icon: "lucide:link-2" }, { id: "checks", label: "约束", icon: "lucide:badge-check" }, { id: "ddl", label: "DDL 预览", icon: "lucide:file-code-2" }] as const;
</script>

<template>
  <section v-if="tab.spec" class="designer-view">
    <header class="view-header"><div><Icon icon="lucide:panel-top-open" /><span><strong>{{ tab.title }}</strong><small>{{ tab.database }}{{ tab.schema ? ` · ${tab.schema}` : '' }}</small></span></div><label class="table-name">表名<input :value="tab.spec.table" @input="emit('update', { table: ($event.target as HTMLInputElement).value })" /></label><button @click="emit('preview')"><Icon icon="lucide:file-scan" />生成 DDL</button><button class="primary" :disabled="!tab.statements.length" @click="emit('apply')"><Icon icon="lucide:save" />保存</button></header>
    <nav class="designer-tabs"><button v-for="pane in panes" :key="pane.id" :class="{ current: tab.pane === pane.id }" @click="emit('pane', pane.id)"><Icon :icon="pane.icon" />{{ pane.label }}<span v-if="pane.id === 'columns'">{{ tab.spec.columns.length }}</span></button></nav>
    <div v-if="tab.error" class="inline-error">{{ tab.error }}</div>
    <div v-if="tab.pane === 'columns'" class="designer-pane">
      <div class="designer-actions"><button @click="addColumn"><Icon icon="lucide:plus" />添加字段</button><span>双击或直接修改单元格内容</span></div><div class="structure-table">
        <table>
          <thead><tr><th>#</th><th>字段名</th><th>类型</th><th>NULL</th><th>主键</th><th>默认值</th><th>额外</th><th>生成表达式</th><th>注释</th><th /></tr></thead><tbody>
            <tr v-for="(column, index) in tab.spec.columns" :key="index"><td>{{ index + 1 }}</td><td><input :value="column.name" @input="setColumn(index,{name:($event.target as HTMLInputElement).value})" /></td><td><input :value="column.data_type" @input="setColumn(index,{data_type:($event.target as HTMLInputElement).value})" /></td><td><input type="checkbox" :checked="column.nullable" @change="setColumn(index,{nullable:($event.target as HTMLInputElement).checked})" /></td><td><input type="checkbox" :checked="tab.spec.primary_key.includes(column.name)" @change="setPrimary(column.name,($event.target as HTMLInputElement).checked)" /></td><td><input :value="String(column.default ?? '')" @input="setColumn(index,{default:($event.target as HTMLInputElement).value || null})" /></td><td><input :value="column.extra" @input="setColumn(index,{extra:($event.target as HTMLInputElement).value})" /></td><td><input :value="column.generation || ''" @input="setColumn(index,{generation:($event.target as HTMLInputElement).value})" /></td><td><input :value="column.comment" @input="setColumn(index,{comment:($event.target as HTMLInputElement).value})" /></td><td><button class="icon-danger" @click="removeColumn(index)"><Icon icon="lucide:trash-2" /></button></td></tr>
          </tbody>
        </table>
      </div>
    </div>
    <div v-if="tab.pane === 'indexes'" class="designer-pane"><div class="designer-actions"><button @click="emit('update',{indexes:[...tab.spec.indexes,{name:`idx_${tab.spec.indexes.length+1}`,unique:false,type:'BTREE',columns:[]}]})"><Icon icon="lucide:plus" />添加索引</button></div><div class="structure-table compact"><table><thead><tr><th>#</th><th>名称</th><th>唯一</th><th>类型</th><th>字段（逗号分隔）</th><th /></tr></thead><tbody><tr v-for="(item,index) in tab.spec.indexes" :key="index"><td>{{ index+1 }}</td><td><input :value="item.name" @input="setIndex(index,{name:($event.target as HTMLInputElement).value})" /></td><td><input type="checkbox" :checked="item.unique" @change="setIndex(index,{unique:($event.target as HTMLInputElement).checked})" /></td><td><select :value="item.type" @change="setIndex(index,{type:($event.target as HTMLSelectElement).value})"><option>BTREE</option><option>HASH</option><option>FULLTEXT</option></select></td><td><input :value="item.columns.join(', ')" @input="setIndex(index,{columns:($event.target as HTMLInputElement).value.split(',').map(v=>v.trim()).filter(Boolean)})" /></td><td><button class="icon-danger" @click="emit('update',{indexes:tab.spec.indexes.filter((_,row)=>row!==index)})"><Icon icon="lucide:trash-2" /></button></td></tr></tbody></table></div></div>
    <div v-if="tab.pane === 'foreign'" class="designer-pane"><div class="designer-actions"><button @click="emit('update',{foreign_keys:[...tab.spec.foreign_keys,{name:`fk_${tab.spec.foreign_keys.length+1}`,columns:[],referenced_schema:tab.spec.engine==='PostgreSQL'?tab.schema:'',referenced_table:'',referenced_columns:[],on_delete:'RESTRICT',on_update:'RESTRICT'}]})"><Icon icon="lucide:plus" />添加外键</button></div><div class="structure-table compact"><table><thead><tr><th>名称</th><th>本表字段</th><th v-if="tab.spec.engine==='PostgreSQL'">引用 Schema</th><th>引用表</th><th>引用字段</th><th>ON DELETE</th><th>ON UPDATE</th><th /></tr></thead><tbody><tr v-for="(item,index) in tab.spec.foreign_keys" :key="index"><td><input :value="item.name" @input="setForeign(index,{name:($event.target as HTMLInputElement).value})" /></td><td><input :value="item.columns.join(',')" @input="setForeign(index,{columns:($event.target as HTMLInputElement).value.split(',').map(v=>v.trim()).filter(Boolean)})" /></td><td v-if="tab.spec.engine==='PostgreSQL'"><input :value="item.referenced_schema || tab.schema" @input="setForeign(index,{referenced_schema:($event.target as HTMLInputElement).value})" /></td><td><input :value="item.referenced_table" @input="setForeign(index,{referenced_table:($event.target as HTMLInputElement).value})" /></td><td><input :value="item.referenced_columns.join(',')" @input="setForeign(index,{referenced_columns:($event.target as HTMLInputElement).value.split(',').map(v=>v.trim()).filter(Boolean)})" /></td><td><select :value="item.on_delete" @change="setForeign(index,{on_delete:($event.target as HTMLSelectElement).value})"><option>RESTRICT</option><option>CASCADE</option><option>SET NULL</option><option>NO ACTION</option></select></td><td><select :value="item.on_update" @change="setForeign(index,{on_update:($event.target as HTMLSelectElement).value})"><option>RESTRICT</option><option>CASCADE</option><option>SET NULL</option><option>NO ACTION</option></select></td><td><button class="icon-danger" @click="emit('update',{foreign_keys:tab.spec.foreign_keys.filter((_,row)=>row!==index)})"><Icon icon="lucide:trash-2" /></button></td></tr></tbody></table></div></div>
    <div v-if="tab.pane === 'checks'" class="designer-pane"><div class="designer-actions"><button @click="emit('update',{checks:[...tab.spec.checks,{name:`chk_${tab.spec.checks.length+1}`,clause:''}]})"><Icon icon="lucide:plus" />添加 CHECK</button></div><div class="structure-table compact"><table><thead><tr><th>名称</th><th>检查表达式</th><th /></tr></thead><tbody><tr v-for="(item,index) in tab.spec.checks" :key="index"><td><input :value="item.name" @input="setCheck(index,{name:($event.target as HTMLInputElement).value})" /></td><td><input :value="item.clause" placeholder="amount >= 0" @input="setCheck(index,{clause:($event.target as HTMLInputElement).value})" /></td><td><button class="icon-danger" @click="emit('update',{checks:tab.spec.checks.filter((_,row)=>row!==index)})"><Icon icon="lucide:trash-2" /></button></td></tr></tbody></table></div></div>
    <div v-if="tab.pane === 'ddl'" class="ddl-pane"><div v-if="tab.dangerous.length" class="danger-banner"><Icon icon="lucide:triangle-alert" /><span><b>检测到危险操作</b><small>{{ tab.dangerous.length }} 条语句可能删除或重建结构</small></span></div><template v-if="tab.statements.length"><div v-for="(statement,index) in tab.statements" :key="index" class="ddl-block"><header>语句 {{ index+1 }}<span v-if="tab.dangerous.includes(statement)">危险</span></header><pre>{{ statement }};</pre></div></template><div v-else class="empty-ddl"><Icon icon="lucide:file-code-2" /><b>尚未生成 DDL</b><p>修改结构后点击“生成 DDL”。</p></div></div>
    <footer class="table-options"><template v-if="tab.spec.engine==='PostgreSQL'"><label>引擎<input value="PostgreSQL" disabled /></label><label>字符集<input value="UTF8" disabled /></label><label>Schema<input :value="tab.spec.schema" disabled /></label></template><template v-else><label>引擎<select :value="tab.spec.engine" @change="emit('update',{engine:($event.target as HTMLSelectElement).value})"><option>InnoDB</option><option>MyISAM</option><option>MEMORY</option></select></label><label>字符集<select :value="tab.spec.charset" @change="emit('update',{charset:($event.target as HTMLSelectElement).value})"><option>utf8mb4</option><option>utf8</option><option>latin1</option></select></label><label>排序规则<input :value="tab.spec.collation" @input="emit('update',{collation:($event.target as HTMLInputElement).value})" /></label></template><label class="grow">表注释<input :value="tab.spec.comment" @input="emit('update',{comment:($event.target as HTMLInputElement).value})" /></label></footer>
  </section>
</template>
