<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { computed, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import ContextMenu from "./components/ContextMenu.vue";
import DatabaseTree from "./components/DatabaseTree.vue";
import EditableGrid from "./components/EditableGrid.vue";
import ObjectList from "./components/ObjectList.vue";
import SqlEditor from "./components/SqlEditor.vue";
import TableDesigner from "./components/TableDesigner.vue";
import { API_BASE, ApiError, api, authToken, download, isNetworkError, isSessionExpiredError, jsonBody, workspaceId } from "./api";
import type { Catalog, DataTab, Database, DbObject, DesignerTab, MenuState, Objects, ObjectsTab, Profile, QueryResponse, QueryTab, ResultSet, TableData, TableSchema, TableSpec, WizardState, WorkTab } from "./types";

const user = ref(""); const authReady = ref(false); const loginUser = ref("admin"); const loginPassword = ref(""); const loginError = ref(""); const loginLoading = ref(false);
const profile = ref<Profile>(); const serverExpanded = ref(true); const databases = ref<Database[]>([]); const database = ref(""); const expanded = ref(new Set<string>()); const objects = ref<Record<string, Objects>>({}); const catalogs = ref<Record<string, Catalog>>({}); const treeFilter = ref("");
const tabs = ref<WorkTab[]>([]); const activeId = ref(""); const notice = ref(""); const noticeError = ref(false); const fatal = ref(""); const contextMenu = ref<MenuState | null>(null); const inspector = ref<{ title: string; subtitle: string; lines: string[] }>();
const resultPane = ref<string>("result-0"); const historyOpen = ref(false); const history = ref<string[]>([]); const savedQueries = ref<{ name:string; database:string; sql:string }[]>([]); const editorRef = ref<{ formatSql: () => void; focus: () => void }>();
const queryViewRef = ref<HTMLElement>(); const queryEditorHeight = ref(260); let stopEditorResize: (() => void) | undefined;
const resultGridRef = ref<{ setWidth: (column: string, width: number) => void; autoFit: (column: string) => void; autoFitAll: () => void; setRowHeight: (height: number) => void; freeze: (column: string) => void; unfreeze: () => void; selectAll: () => void; deselectAll: () => void; goToRow: (row: number) => void }>();
const rowDialog = ref<{ mode: "insert"; tabId: string; values: Record<string, unknown> }>(); const wizard = ref<WizardState>(); const wizardStep = ref(1); const wizardFormat = ref("csv"); const wizardCount = ref(100); const wizardIncludeData = ref(true); const wizardFile = ref<File>(); const wizardRunning = ref(false); const jobProgress = ref({ value: 0, message: "" }); const activeJobId = ref("");
const searchDialog = ref<{ term: string; rows: { kind: string; name: string; detail: string }[] }>();
const createDatabaseDialog = ref<{ name: string; charset: string; collation: string; saving: boolean }>();
const connectionState = ref<"online" | "checking" | "offline">("checking"); const reconnecting = ref(false); let heartbeatId = 0;
const uid = () => crypto.randomUUID().slice(0, 8);
const active = computed(() => tabs.value.find(tab => tab.id === activeId.value));
const activeData = computed(() => active.value?.type === "data" ? active.value : undefined);
const activeDesigner = computed(() => active.value?.type === "designer" ? active.value : undefined);
const activeObjectsTab = computed(() => active.value?.type === "objects" ? active.value : undefined);
const activeResult = computed<ResultSet | undefined>(() => { const tab = active.value; if (tab?.type !== "query") return; const index = Number(resultPane.value.replace("result-", "")); return tab.response?.results[index]; });
const connectionLabel = computed(() => connectionState.value === "online" ? "已连接" : connectionState.value === "checking" ? "正在重连" : "已断开");

onMounted(async () => {
  try { history.value = JSON.parse(localStorage.getItem("deebee_history") || "[]"); savedQueries.value = JSON.parse(localStorage.getItem("deebee_saved_queries") || "[]"); } catch { history.value = []; savedQueries.value = []; }
  const savedHeight = Number(localStorage.getItem("deebee_query_editor_height")); if (Number.isFinite(savedHeight) && savedHeight > 0) queryEditorHeight.value = savedHeight;
  if (authToken()) { user.value = "admin"; await bootstrap(); }
  authReady.value = true;
  heartbeatId = window.setInterval(() => { if (!document.hidden) void checkConnection(false); }, 15000);
  window.addEventListener("online", reconnectAfterNetwork); window.addEventListener("offline", markOffline); document.addEventListener("visibilitychange", reconnectWhenVisible);
});
onBeforeUnmount(() => { stopEditorResize?.(); window.clearInterval(heartbeatId); window.removeEventListener("online", reconnectAfterNetwork); window.removeEventListener("offline", markOffline); document.removeEventListener("visibilitychange", reconnectWhenVisible); });

function errorText(reason: unknown) { return reason instanceof Error ? reason.message : "操作失败"; }
function flash(message: string, error = false) { notice.value = message; noticeError.value = error; window.setTimeout(() => { if (notice.value === message) notice.value = ""; }, 2800); }
function flashError(reason: unknown) { if (isNetworkError(reason)) connectionState.value = "offline"; flash(`错误：${errorText(reason)}`, true); }
function updateTab(id: string, patch: Partial<WorkTab>) { const tab = tabs.value.find(item => item.id === id); if (tab) Object.assign(tab, patch); }
function closeMenu() { contextMenu.value = null; }
function markOffline() { if (user.value) connectionState.value = "offline"; }
function reconnectAfterNetwork() { void checkConnection(false); }
function reconnectWhenVisible() { if (!document.hidden) void checkConnection(false); }
function shouldRecreateSession(reason: unknown) { return isSessionExpiredError(reason) || (reason instanceof ApiError && [2006, 2013, 2055].includes(reason.code || 0)); }
async function recreateQuerySession(tab: QueryTab) {
  if (!profile.value) throw new Error("数据库连接尚未初始化");
  const session = await api<{ id: string }>("/sessions", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: tab.database, autocommit: tab.autocommit, workspace_id: workspaceId() }) });
  tab.sessionId = session.id; return session.id;
}
async function ensureQuerySession(tab: QueryTab) {
  try { await api(`/sessions/${tab.sessionId}`); return false; }
  catch (reason) { if (!shouldRecreateSession(reason)) throw reason; await recreateQuerySession(tab); return true; }
}
async function checkConnection(showFeedback: boolean) {
  if (!user.value || reconnecting.value) return connectionState.value === "online";
  const previous = connectionState.value; reconnecting.value = true; if (showFeedback || previous === "offline") connectionState.value = "checking";
  try {
    await api("/health");
    const rebuilt = (await Promise.all(tabs.value.filter((tab): tab is QueryTab => tab.type === "query").map(ensureQuerySession))).filter(Boolean).length;
    connectionState.value = "online";
    if (previous === "offline" || rebuilt) { for (const tab of tabs.value) if (tab.type === "query" && tab.error?.includes("连接中断")) tab.error = "连接已恢复，本条 SQL 未自动重放，请重新执行。"; flash(rebuilt ? `连接已恢复，已重建 ${rebuilt} 个查询会话` : "后台连接已恢复"); }
    else if (showFeedback) flash("连接正常");
    return true;
  } catch (reason) {
    connectionState.value = "offline"; if (showFeedback) flashError(reason); return false;
  } finally { reconnecting.value = false; }
}
function editorHeightLimit() { return Math.max(160, (queryViewRef.value?.clientHeight || innerHeight) - 165); }
function setEditorHeight(value: number) { queryEditorHeight.value = Math.round(Math.min(editorHeightLimit(), Math.max(120, value))); localStorage.setItem("deebee_query_editor_height", String(queryEditorHeight.value)); }
function resizeEditorByKeyboard(event: KeyboardEvent) {
  if (!["ArrowUp", "ArrowDown", "Home", "End"].includes(event.key)) return;
  event.preventDefault();
  if (event.key === "Home") setEditorHeight(120); else if (event.key === "End") setEditorHeight(editorHeightLimit()); else setEditorHeight(queryEditorHeight.value + (event.key === "ArrowDown" ? 18 : -18));
}
function startEditorResize(event: PointerEvent) {
  if (event.button !== 0) return;
  event.preventDefault(); const startY = event.clientY; const startHeight = queryEditorHeight.value;
  const move = (next: PointerEvent) => setEditorHeight(startHeight + next.clientY - startY);
  const stop = () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); document.body.classList.remove("resizing-query"); stopEditorResize = undefined; editorRef.value?.focus(); };
  stopEditorResize?.(); stopEditorResize = stop; document.body.classList.add("resizing-query"); window.addEventListener("pointermove", move); window.addEventListener("pointerup", stop, { once: true });
}
function selectTab(tab: WorkTab) { activeId.value = tab.id; database.value = tab.database; if (tab.type === "query") resultPane.value = tab.response?.results.some(result => result.kind === "rows") ? `result-${tab.response.results.findIndex(result => result.kind === "rows")}` : "message"; }

async function login() {
  loginLoading.value = true; loginError.value = "";
  try { const result = await api<{ token: string; user: { username: string } }>("/auth/login", { method: "POST", body: jsonBody({ username: loginUser.value, password: loginPassword.value }) }); sessionStorage.setItem("deebee_token", result.token); user.value = result.user.username; await bootstrap(); }
  catch (reason) { loginError.value = errorText(reason); } finally { loginLoading.value = false; }
}
function logout() { sessionStorage.removeItem("deebee_token"); user.value = ""; tabs.value = []; profile.value = undefined; connectionState.value = "offline"; }
async function bootstrap() {
  try {
    const profiles = await api<Profile[]>("/connections"); await api("/sessions/cleanup", { method: "POST", body: jsonBody({ workspace_id: workspaceId() }) });
    if (!profiles[0]) throw new Error("没有可用的数据库连接"); profile.value = profiles[0];
    databases.value = await api<Database[]>(`/connections/${profile.value.id}/databases`);
    const initial = databases.value.find(item => item.name === profile.value!.default_database)?.name || databases.value[0]?.name || "";
    database.value = initial; expanded.value = new Set(initial ? [initial] : []);
    if (initial) { await loadObjects(initial); await newQuery(initial); } connectionState.value = "online";
  } catch (reason) { if (errorText(reason).includes("登录")) logout(); else fatal.value = errorText(reason); }
}
async function loadObjects(db: string) {
  if (!profile.value) return;
  const [payload, catalog] = await Promise.all([
    api<Objects>(`/connections/${profile.value.id}/databases/${encodeURIComponent(db)}/objects`),
    api<Catalog>(`/connections/${profile.value.id}/databases/${encodeURIComponent(db)}/catalog`),
  ]);
  objects.value = { ...objects.value, [db]: payload }; catalogs.value = { ...catalogs.value, [db]: catalog };
}
async function chooseDatabase(name: string) {
  database.value = name; const next = new Set(expanded.value); next.add(name); expanded.value = next;
  try { if (!objects.value[name] || !catalogs.value[name]) await loadObjects(name); const tab = active.value; if (tab?.type === "query" && tab.database !== name) await switchQueryDatabase(tab, name); }
  catch (reason) { flashError(reason); }
}
async function toggleDatabase(name: string) {
  const next = new Set(expanded.value);
  if (next.has(name)) next.delete(name); else { next.add(name); if (!objects.value[name]) await loadObjects(name); }
  expanded.value = next;
}
async function switchQueryDatabase(tab: QueryTab, db: string) {
  if (!profile.value || tab.database === db) return;
  updateTab(tab.id, { loading: true, error: undefined });
  try {
    if (!catalogs.value[db]) await loadObjects(db);
    const session = await api<{ id: string }>("/sessions", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: db, autocommit: tab.autocommit, workspace_id: workspaceId() }) });
    const old = tab.sessionId; updateTab(tab.id, { database: db, sessionId: session.id, response: undefined, loading: false });
    void api(`/sessions/${old}`, { method: "DELETE" }).catch(() => undefined); database.value = db; resultPane.value = "message"; flash(`查询标签已切换到 ${db}`);
  } catch (reason) { updateTab(tab.id, { loading: false, error: errorText(reason) }); flashError(reason); }
}
async function newQuery(db = database.value, sql = "SELECT 1 AS ready;") {
  if (!profile.value || !db) return;
  try { if (!catalogs.value[db]) await loadObjects(db); const session = await api<{ id: string }>("/sessions", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: db, autocommit: true, workspace_id: workspaceId() }) }); const count = tabs.value.filter(tab => tab.type === "query").length + 1; const tab: QueryTab = { id: uid(), type: "query", title: `查询 ${count}`, database: db, sessionId: session.id, sql, autocommit: true, loading: false, resultIndex: 0 }; tabs.value.push(tab); activeId.value = tab.id; resultPane.value = "message"; }
  catch (reason) { flashError(reason); }
}
async function closeTab(tab: WorkTab) { if (tab.type === "query") void api(`/sessions/${tab.sessionId}`, { method: "DELETE" }).catch(() => undefined); const index = tabs.value.indexOf(tab); tabs.value.splice(index, 1); if (activeId.value === tab.id) activeId.value = tabs.value[Math.max(0, index - 1)]?.id || ""; }
function tabMenu(event: MouseEvent, tab: WorkTab) { const index=tabs.value.indexOf(tab); contextMenu.value={x:event.clientX,y:event.clientY,title:"标签操作",items:[{id:"close",label:"关闭",icon:"lucide:x",action:()=>closeTab(tab)},{id:"other",label:"关闭其他标签",icon:"lucide:copy-x",action:()=>tabs.value.filter(item=>item!==tab).forEach(closeTab)},{id:"right",label:"关闭右侧标签",icon:"lucide:panel-right-close",disabled:index===tabs.value.length-1,action:()=>[...tabs.value.slice(index+1)].forEach(closeTab)},{id:"duplicate",label:"复制标签",icon:"lucide:copy",action:()=>tab.type==="query"?newQuery(tab.database,tab.sql):undefined},{id:"save",label:"保存查询…",icon:"lucide:save",disabled:tab.type!=="query",action:()=>{if(tab.type!=="query")return;const name=prompt("查询名称",tab.title);if(!name)return;savedQueries.value=[{name,database:tab.database,sql:tab.sql},...savedQueries.value.filter(item=>item.name!==name)];localStorage.setItem("deebee_saved_queries",JSON.stringify(savedQueries.value));flash(`查询 ${name} 已保存`)}}]}; }
async function useSavedQuery(item:{name:string;database:string;sql:string}){const tab=active.value;if(tab?.type!=="query")return;await switchQueryDatabase(tab,item.database);tab.sql=item.sql;historyOpen.value=false}

async function sendQuery(tab: QueryTab, sql: string) { return api<QueryResponse>(`/sessions/${tab.sessionId}/query`, { method: "POST", body: jsonBody({ sql, limit: 10000 }) }); }
function acceptQueryResponse(tab: QueryTab, sql: string, response: QueryResponse) {
  updateTab(tab.id, { response, loading: false, autocommit: response.autocommit }); const firstRows = response.results.findIndex(result => result.kind === "rows"); resultPane.value = firstRows >= 0 ? `result-${firstRows}` : "message"; history.value = [sql, ...history.value.filter(item => item !== sql)].slice(0, 100); localStorage.setItem("deebee_history", JSON.stringify(history.value)); connectionState.value = "online";
}
async function runQuery(tab: QueryTab, sql = tab.sql) {
  if (!sql.trim()) return; updateTab(tab.id, { loading: true, error: undefined }); resultPane.value = "message";
  try { acceptQueryResponse(tab, sql, await sendQuery(tab, sql)); }
  catch (reason) {
    let failure = reason;
    if (shouldRecreateSession(reason)) {
      try { await recreateQuerySession(tab); acceptQueryResponse(tab, sql, await sendQuery(tab, sql)); flash("查询会话已自动重连"); return; }
      catch (retryReason) { failure = retryReason; }
    }
    if (isNetworkError(failure)) { connectionState.value = "offline"; updateTab(tab.id, { loading: false, error: "后台连接中断，正在自动重连。本条 SQL 未自动重放。" }); void checkConnection(false); }
    else updateTab(tab.id, { loading: false, error: errorText(failure) });
    resultPane.value = "message";
  }
}
async function cancelQuery(tab: QueryTab) { try { const result = await api<{ cancelled: boolean }>(`/sessions/${tab.sessionId}/cancel`, { method: "POST" }); flash(result.cancelled ? "查询已取消" : "当前没有运行中的查询"); } catch (reason) { flashError(reason); } }
async function transaction(tab: QueryTab, action: "commit" | "rollback") { try { await api(`/sessions/${tab.sessionId}/${action}`, { method: "POST" }); flash(action === "commit" ? "事务已提交" : "事务已回滚"); } catch (reason) { flashError(reason); } }
async function toggleAutocommit(tab: QueryTab) { try { await api(`/sessions/${tab.sessionId}/autocommit`, { method: "PATCH", body: jsonBody({ enabled: !tab.autocommit }) }); tab.autocommit = !tab.autocommit; flash(tab.autocommit ? "已开启自动提交" : "已进入手动事务模式"); } catch (reason) { flashError(reason); } }

async function openData(table: string, db = database.value) {
  const existing = tabs.value.find(tab => tab.type === "data" && tab.database === db && tab.table === table); if (existing) return selectTab(existing);
  const tab = reactive<DataTab>({ id: uid(), type: "data", title: table, database: db, table, loading: true, page: 1, filterColumn: "", filterValue: "", selected: null }); tabs.value.push(tab); activeId.value = tab.id; database.value = db; await loadData(tab);
}
async function loadData(tab: DataTab, overrides: Partial<DataTab> = {}) {
  if (!profile.value) return; Object.assign(tab, overrides, { loading: true, error: undefined });
  try { const filters = tab.filterColumn && tab.filterValue ? [{ column: tab.filterColumn, operator: "contains", value: tab.filterValue }] : []; tab.data = await api<TableData>("/data/read", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: tab.database, table: tab.table, page: tab.page, page_size: 100, filters, sort: tab.sort }) }); tab.loading = false; tab.selected = null; }
  catch (reason) { tab.loading = false; tab.error = errorText(reason); }
}
async function saveInline(tab: DataTab, rowIndex: number, changes: Record<string, unknown>) {
  if (!profile.value || !tab.data) return; const row = tab.data.rows[rowIndex]; const key = Object.fromEntries(tab.data.primary_key.map(field => [field, row[field]]));
  if (!Object.keys(key).length) return flash("该表没有主键，不能安全地原地编辑", true);
  try { await api("/data/rows", { method: "PATCH", body: jsonBody({ profile_id: profile.value.id, database: tab.database, table: tab.table, key, changes }) }); Object.assign(row, changes); flash("单元格修改已保存"); }
  catch (reason) { flashError(reason); await loadData(tab); }
}
async function insertRow(tab: DataTab) {
  if (!profile.value || !rowDialog.value) return;
  try { const values = Object.fromEntries(Object.entries(rowDialog.value.values).filter(([,value]) => value !== "")); await api("/data/rows", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: tab.database, table: tab.table, values }) }); rowDialog.value = undefined; await loadData(tab); flash("记录已添加"); } catch (reason) { flashError(reason); }
}
async function deleteRow(tab: DataTab) { if (!profile.value || tab.selected == null || !tab.data) return flash("请先选择一行"); const row = tab.data.rows[tab.selected]; const key = Object.fromEntries(tab.data.primary_key.map(field => [field, row[field]])); if (!confirm("确定删除选中记录吗？")) return; try { await api("/data/rows", { method: "DELETE", body: jsonBody({ profile_id: profile.value.id, database: tab.database, table: tab.table, key }) }); await loadData(tab); flash("记录已删除"); } catch (reason) { flashError(reason); } }
function sortData(tab: DataTab, column: string) { const direction = tab.sort?.column === column && tab.sort.direction === "asc" ? "desc" : "asc"; void loadData(tab, { sort: { column, direction }, page: 1 }); }
function reloadActiveData(overrides: Partial<DataTab> = {}) { if (activeData.value) void loadData(activeData.value, overrides); }
function deleteActiveRow() { if (activeData.value) void deleteRow(activeData.value); }
function saveActiveInline(row: number, changes: Record<string, unknown>) { if (activeData.value) void saveInline(activeData.value, row, changes); }
function sortActiveData(column: string) { if (activeData.value) sortData(activeData.value, column); }
function insertActiveRow() { if (activeData.value) void insertRow(activeData.value); }

async function openDesigner(table?: string, db = database.value) {
  if (!profile.value || !db) return; const existing = tabs.value.find(tab => tab.type === "designer" && tab.database === db && tab.currentTable === (table || null)); if (existing) return selectTab(existing);
  const tab = reactive<DesignerTab>({ id: uid(), type: "designer", title: table ? `${table} — 设计` : "新建表", database: db, table: table || "new_table", currentTable: table || null, loading: true, pane: "columns", statements: [], dangerous: [] }); tabs.value.push(tab); activeId.value = tab.id;
  try { let source: TableSchema | undefined; if (table) source = await api<TableSchema>(`/schema/${profile.value.id}/${encodeURIComponent(db)}/${encodeURIComponent(table)}`); tab.source = source; tab.spec = source ? { database: db, table: source.table, columns: source.columns, primary_key: source.primary_key, indexes: source.indexes, foreign_keys: source.foreign_keys, checks: source.checks, engine: source.engine, charset: source.charset, collation: source.collation, comment: source.comment } : { database: db, table: "new_table", columns: [{ name: "id", data_type: "BIGINT UNSIGNED", nullable: false, default: null, extra: "AUTO_INCREMENT", comment: "", generation: "" }], primary_key: ["id"], indexes: [], foreign_keys: [], checks: [], engine: "InnoDB", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", comment: "" }; tab.loading = false; }
  catch (reason) { tab.loading = false; tab.error = errorText(reason); }
}
function updateSpec(tab: DesignerTab, patch: Partial<TableSpec>) { if (tab.spec) tab.spec = { ...tab.spec, ...patch }; tab.statements = []; tab.dangerous = []; }
async function previewDdl(tab: DesignerTab) { if (!profile.value || !tab.spec) return; tab.loading = true; try { const result = await api<{ statements: string[]; dangerous: string[] }>("/ddl/preview", { method: "POST", body: jsonBody({ profile_id: profile.value.id, spec: tab.spec, current_table: tab.currentTable }) }); tab.statements = result.statements; tab.dangerous = result.dangerous; tab.pane = "ddl"; } catch (reason) { tab.error = errorText(reason); } finally { tab.loading = false; } }
async function applyDdl(tab: DesignerTab) { if (!profile.value || !tab.spec || !tab.statements.length) return; if (tab.dangerous.length && !confirm("检测到危险结构变更，确定执行吗？")) return; try { await api("/ddl/apply", { method: "POST", body: jsonBody({ profile_id: profile.value.id, spec: tab.spec, current_table: tab.currentTable, expected_statements: tab.statements }) }); tab.currentTable = tab.spec.table; tab.title = `${tab.spec.table} — 设计`; tab.statements = []; tab.dangerous = []; await loadObjects(tab.database); flash("表结构已保存"); } catch (reason) { flashError(reason); } }

function openList(kind: keyof Objects, db: string) { const id = `objects:${db}:${kind}`; const existing = tabs.value.find(tab => tab.id === id); if (existing) return selectTab(existing); const labels = { tables: "表", views: "视图", routines: "函数与过程", triggers: "触发器", events: "事件" }; const tab: ObjectsTab = { id, type: "objects", title: labels[kind], database: db, kind }; tabs.value.push(tab); activeId.value = id; }
async function openObject(kind: string, item: DbObject, db: string) { if (!profile.value) return; const normalized = kind === "routines" ? item.object_type.toLowerCase() : kind.replace(/s$/, ""); try { const result = await api<{ sql: string }>(`/objects/${profile.value.id}/${encodeURIComponent(db)}/${normalized}/${encodeURIComponent(item.name)}/ddl`); await newQuery(db, result.sql); } catch (reason) { flashError(reason); } }
function inspect(item: DbObject, db: string) { inspector.value = { title: item.name, subtitle: `${db} · ${item.object_type}`, lines: [`预计行数：${item.estimated_rows ?? "—"}`, `引擎：${item.engine || "—"}`, `数据大小：${item.data_length ?? "—"}`, `索引大小：${item.index_length ?? "—"}`, `排序规则：${item.collation || "—"}`, `创建时间：${item.created_at || "—"}`, `更新时间：${item.updated_at || "—"}`, `注释：${item.comment || "—"}`] }; }

async function refreshDatabase(db: string) { try { await loadObjects(db); flash(`${db} 已刷新`); } catch (reason) { flashError(reason); } }
function openCreateDatabase() { createDatabaseDialog.value = { name: "", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", saving: false }; }
async function refreshServer() { if (!profile.value) return; try { databases.value = await api<Database[]>(`/connections/${profile.value.id}/databases`); flash(`${profile.value.name} 已刷新`); } catch (reason) { flashError(reason); } }
async function createDatabase() {
  const dialog = createDatabaseDialog.value;
  if (!profile.value || !dialog || !dialog.name.trim()) return;
  dialog.saving = true;
  try {
    const name = dialog.name.trim();
    await api("/databases", { method: "POST", body: jsonBody({ profile_id: profile.value.id, name, charset: dialog.charset, collation: dialog.collation }) });
    databases.value = await api<Database[]>(`/connections/${profile.value.id}/databases`);
    serverExpanded.value = true; database.value = name; expanded.value = new Set([...expanded.value, name]);
    await loadObjects(name); createDatabaseDialog.value = undefined; flash(`数据库 ${name} 已创建`);
  } catch (reason) { flashError(reason); } finally { if (createDatabaseDialog.value) createDatabaseDialog.value.saving = false; }
}
function serverMenu(event: MouseEvent) {
  if (!profile.value) return;
  contextMenu.value = { x: event.clientX, y: event.clientY, title: `${profile.value.name} 服务器操作`, items: [
    { id:"toggle", label:serverExpanded.value?"收起服务器":"展开服务器", icon:"lucide:server", action:()=>serverExpanded.value=!serverExpanded.value },
    { id:"properties", label:"连接属性…", icon:"lucide:settings-2", action:()=>inspector.value={title:profile.value!.name,subtitle:"MySQL 数据库服务器",lines:[`主机：${profile.value!.host}`,`端口：${profile.value!.port}`,`用户：${profile.value!.user}`,`默认数据库：${profile.value!.default_database || "—"}`]} },
    { id:"test", label:"测试连接", icon:"lucide:plug-zap", action:()=>api(`/connections/${profile.value!.id}/test`,{method:"POST"}).then(()=>flash("连接成功")).catch(flashError) },
    { id:"s1", separator:true },
    { id:"new-db", label:"新建数据库…", icon:"lucide:database-backup", action:openCreateDatabase },
    { id:"query", label:"新建查询", icon:"lucide:square-terminal", action:()=>newQuery() },
    { id:"refresh", label:"刷新", icon:"lucide:refresh-cw", action:refreshServer },
  ] };
}
async function tableAction(db: string, table: string, action: string, target = "", withData = false) { if (!profile.value) return; try { const result = await api<{ results?: Record<string,unknown>[] }>("/objects/table/action", { method: "POST", body: jsonBody({ profile_id: profile.value.id, database: db, table, action, target, with_data: withData }) }); if (["drop","rename","duplicate"].includes(action)) await loadObjects(db); const tab = tabs.value.find(item => item.type === "data" && item.database === db && item.table === table); if (tab?.type === "data" && ["empty","truncate"].includes(action)) await loadData(tab); if (result.results?.length) inspector.value = { title: `${table} · 维护`, subtitle: action.toUpperCase(), lines: result.results.map(row => Object.values(row).join(" · ")) }; flash(`${table}：操作已完成`); } catch (reason) { flashError(reason); } }
function databaseMenu(event: MouseEvent, db: Database) { database.value = db.name; contextMenu.value = { x: event.clientX, y: event.clientY, title: `${db.name} 数据库操作`, items: [
  { id:"toggle",label:expanded.value.has(db.name)?"关闭数据库":"打开数据库",icon:"lucide:database",action:()=>toggleDatabase(db.name) }, { id:"properties",label:"编辑数据库…",icon:"lucide:info",action:()=>inspector.value={title:db.name,subtitle:"数据库属性",lines:[`字符集：${db.charset}`,`排序规则：${db.collation}`]} }, { id:"new-db",label:"新建数据库…",icon:"lucide:database-backup",action:openCreateDatabase }, { id:"drop-db",label:"删除数据库",icon:"lucide:trash-2",danger:true,action:async()=>{if(!profile.value||prompt(`输入 ${db.name} 确认删除`)!==db.name)return;await api(`/databases/${profile.value.id}/${encodeURIComponent(db.name)}`,{method:"DELETE"});databases.value=databases.value.filter(item=>item.name!==db.name);flash(`${db.name} 已删除`)} }, {id:"s1",separator:true},
  {id:"query",label:"新建查询",icon:"lucide:square-terminal",shortcut:"⌘Y",action:()=>newQuery(db.name,"")},{id:"console",label:"控制台",icon:"lucide:terminal",action:()=>newQuery(db.name,"SHOW STATUS;\n")},{id:"sql",label:"执行 SQL 文件…",icon:"lucide:file-input",action:()=>openWizard({kind:"sql",database:db.name})},{id:"dump",label:"转储 SQL 文件…",icon:"lucide:download",action:()=>openWizard({kind:"dump",database:db.name})},{id:"print",label:"打印数据库…",icon:"lucide:printer",action:()=>print()},{id:"search",label:"在数据库中查找…",icon:"lucide:search",action:()=>findDatabase(db.name)},{id:"refresh",label:"刷新",icon:"lucide:refresh-cw",shortcut:"⌘R",action:()=>refreshDatabase(db.name)}] };
}
function tableMenu(event: MouseEvent, table: DbObject, db: string) { const confirmAction=(label:string,action:string)=>()=>{if(confirm(`确定${label}表 ${table.name} 吗？`))void tableAction(db,table.name,action)}; contextMenu.value={x:event.clientX,y:event.clientY,title:`${table.name} 表操作`,items:[
  {id:"open",label:"打开表",icon:"lucide:table-2",action:()=>openData(table.name,db)},{id:"design",label:"设计表",icon:"lucide:panel-top-open",action:()=>openDesigner(table.name,db)},{id:"new",label:"新建表",icon:"lucide:plus",action:()=>openDesigner(undefined,db)},{id:"drop",label:"删除表",icon:"lucide:trash-2",danger:true,action:confirmAction("删除","drop")},{id:"empty",label:"清空表",icon:"lucide:eraser",danger:true,action:confirmAction("清空","empty")},{id:"truncate",label:"Truncate 表",icon:"lucide:scissors",danger:true,action:confirmAction("截断","truncate")},
  {id:"duplicate",label:"复制表",icon:"lucide:copy",children:[{id:"structure",label:"仅结构…",icon:"lucide:copy",action:async()=>{const target=prompt("新表名称",`${table.name}_copy`);if(target)await tableAction(db,table.name,"duplicate",target,false)}},{id:"data",label:"结构和数据…",icon:"lucide:copy-plus",action:async()=>{const target=prompt("新表名称",`${table.name}_copy`);if(target)await tableAction(db,table.name,"duplicate",target,true)}}]},
  {id:"priv",label:"查看权限…",icon:"lucide:user-round-cog",action:()=>showPrivileges(db,table.name)},{id:"s1",separator:true},{id:"import",label:"导入向导…",icon:"lucide:file-input",action:()=>openWizard({kind:"import",database:db,table:table.name})},{id:"export",label:"导出向导…",icon:"lucide:file-output",action:()=>openWizard({kind:"export",database:db,table:table.name})},{id:"generate",label:"数据生成…",icon:"lucide:sparkles",action:()=>openWizard({kind:"generate",database:db,table:table.name})},{id:"dump",label:"转储 SQL 文件…",icon:"lucide:download",action:()=>openWizard({kind:"dump",database:db,table:table.name})},{id:"maintain",label:"维护",icon:"lucide:wrench",children:["check","analyze","optimize","repair"].map(action=>({id:action,label:`${action.toUpperCase()} TABLE`,icon:"lucide:wrench",action:()=>tableAction(db,table.name,action)}))},{id:"s2",separator:true},{id:"copy-name",label:"复制名称",icon:"lucide:copy",action:()=>navigator.clipboard.writeText(`\`${db}\`.\`${table.name}\``)},{id:"copy-ddl",label:"复制 DDL",icon:"lucide:clipboard-copy",action:()=>copyDdl(db,"table",table.name)},{id:"rename",label:"重命名…",icon:"lucide:pencil",action:async()=>{const target=prompt("新表名称",table.name);if(target&&target!==table.name)await tableAction(db,table.name,"rename",target)}},{id:"refresh",label:"刷新",icon:"lucide:refresh-cw",action:()=>refreshDatabase(db)}]}; }
function objectMenu(event: MouseEvent, kind: string, item: DbObject, db: string) { const normalized=kind==="routines"?item.object_type.toLowerCase():kind.replace(/s$/,""); const eventItems=normalized==="event"?[{id:"enable",label:"启用事件",icon:"lucide:circle-play",disabled:item.status==="ENABLED",action:()=>objectStateAction(db,normalized,item,"enable")},{id:"disable",label:"禁用事件",icon:"lucide:circle-pause",disabled:item.status==="DISABLED",action:()=>objectStateAction(db,normalized,item,"disable")}]:[]; contextMenu.value={x:event.clientX,y:event.clientY,title:`${item.name} 对象操作`,items:[{id:"open",label:"打开定义",icon:"lucide:file-code",action:()=>openObject(kind,item,db)},{id:"edit",label:"编辑定义 SQL",icon:"lucide:file-pen-line",action:()=>openObject(kind,item,db)},...eventItems,{id:"copy",label:"复制名称",icon:"lucide:copy",action:()=>navigator.clipboard.writeText(item.name)},{id:"ddl",label:"复制 DDL",icon:"lucide:clipboard-copy",action:()=>copyDdl(db,normalized,item.name)},{id:"drop",label:"删除对象",icon:"lucide:trash-2",danger:true,action:async()=>{if(!profile.value||!confirm(`确定删除 ${item.name} 吗？`))return;await api("/objects/action",{method:"POST",body:jsonBody({profile_id:profile.value.id,database:db,kind:normalized,name:item.name,action:"drop"})});await loadObjects(db);flash(`${item.name} 已删除`)}},{id:"refresh",label:"刷新",icon:"lucide:refresh-cw",action:()=>refreshDatabase(db)}]}; }
async function objectStateAction(db:string,kind:string,item:DbObject,action:"enable"|"disable"){if(!profile.value)return;try{await api("/objects/action",{method:"POST",body:jsonBody({profile_id:profile.value.id,database:db,kind,name:item.name,action})});await loadObjects(db);flash(`${item.name} 已${action==="enable"?"启用":"禁用"}`)}catch(reason){flashError(reason)}}
async function copyDdl(db:string,kind:string,name:string){if(!profile.value)return;try{const result=await api<{sql:string}>(`/objects/${profile.value.id}/${encodeURIComponent(db)}/${kind}/${encodeURIComponent(name)}/ddl`);await navigator.clipboard.writeText(result.sql);flash("DDL 已复制")}catch(reason){flashError(reason)}}
async function showPrivileges(db:string,table:string){if(!profile.value)return;try{const rows=await api<Record<string,unknown>[]>(`/privileges/${profile.value.id}/${encodeURIComponent(db)}?table=${encodeURIComponent(table)}`);inspector.value={title:`${table} · 权限`,subtitle:db,lines:rows.map(row=>Object.values(row).join(" · "))}}catch(reason){flashError(reason)}}
async function findDatabase(db:string){if(!profile.value)return;const term=prompt("查找表、字段、视图、函数或触发器");if(!term)return;try{searchDialog.value=await api(`/search/${profile.value.id}/${encodeURIComponent(db)}?term=${encodeURIComponent(term)}`)}catch(reason){flashError(reason)}}
function objectListMenu(event: MouseEvent, item: DbObject) { const tab = activeObjectsTab.value; if (!tab) return; if (tab.kind === "tables") tableMenu(event, item, tab.database); else objectMenu(event, tab.kind, item, tab.database); }

function resultMenu(event: MouseEvent, rowIndex: number, column: string, result: ResultSet) { const row=result.rows?.[rowIndex]||{}; const cols=result.columns?.map(item=>item.name)||[]; const quote=(v:unknown)=>v===null?"NULL":typeof v==="number"?String(v):`'${String(v).replaceAll("'","''")}'`; const copy=(value:string)=>navigator.clipboard.writeText(value).then(()=>flash("已复制到剪贴板")); contextMenu.value={x:event.clientX,y:event.clientY,title:"结果表格操作",items:[{id:"copy-cell",label:"复制单元格",icon:"lucide:copy",action:()=>copy(String(row[column]??""))},{id:"copy-as",label:"复制为",icon:"lucide:clipboard-copy",children:[{id:"insert",label:"INSERT Statement",icon:"lucide:file-plus",action:()=>copy(`INSERT INTO table_name (${cols.map(c=>`\`${c}\``).join(", ")}) VALUES (${cols.map(c=>quote(row[c])).join(", ")});`)},{id:"update",label:"UPDATE Statement",icon:"lucide:file-pen",action:()=>copy(`UPDATE table_name SET ${cols.map(c=>`\`${c}\` = ${quote(row[c])}`).join(", ")} WHERE ...;`)},{id:"tsv-data",label:"Tab Separated Values (Data only)",icon:"lucide:rows-3",action:()=>copy(cols.map(c=>String(row[c]??"")).join("\t"))},{id:"tsv-fields",label:"Tab Separated Values (Field Name only)",icon:"lucide:columns-3",action:()=>copy(cols.join("\t"))},{id:"tsv-all",label:"Tab Separated Values (Field Name and Data)",icon:"lucide:table-2",action:()=>copy(`${cols.join("\t")}\n${cols.map(c=>String(row[c]??"")).join("\t")}`)},{id:"json",label:"JSON",icon:"lucide:braces",action:()=>copy(JSON.stringify(row,null,2))}]},{id:"s1",separator:true},{id:"select-all",label:"全选",icon:"lucide:list-checks",action:()=>resultGridRef.value?.selectAll()},{id:"deselect",label:"取消全选",icon:"lucide:list-x",action:()=>resultGridRef.value?.deselectAll()},{id:"s2",separator:true},{id:"width",label:"设置当前列宽…",icon:"lucide:move-horizontal",action:()=>{const value=Number(prompt("列宽（80-600 像素）","180"));if(value)resultGridRef.value?.setWidth(column,value)}},{id:"fit",label:"自动调整全部列宽",icon:"lucide:scan",action:()=>resultGridRef.value?.autoFitAll()},{id:"height",label:"设置行高…",icon:"lucide:move-vertical",action:()=>{const value=Number(prompt("行高（24-120 像素）","30"));if(value)resultGridRef.value?.setRowHeight(value)}},{id:"s3",separator:true},{id:"freeze",label:"冻结到当前列",icon:"lucide:pin",action:()=>resultGridRef.value?.freeze(column)},{id:"unfreeze",label:"取消冻结所有列",icon:"lucide:pin-off",action:()=>resultGridRef.value?.unfreeze()},{id:"s4",separator:true},{id:"jump",label:"跳转到记录…",icon:"lucide:locate-fixed",action:()=>{const target=Number(prompt("记录号",String(rowIndex+1)));if(target)resultGridRef.value?.goToRow(target-1)}}]}; }
function dataResultMenu(event:MouseEvent,rowIndex:number,column:string,data?:TableData){if(!data)return;resultMenu(event,rowIndex,column,{index:0,kind:"rows",columns:data.columns.map(item=>({name:item.name,type:item.data_type,nullable:item.nullable})),rows:data.rows,row_count:data.rows.length})}

function openWizard(state:WizardState){wizard.value=state;wizardStep.value=1;wizardFormat.value="csv";wizardCount.value=100;wizardIncludeData.value=true;wizardFile.value=undefined;jobProgress.value={value:0,message:""}}
async function runBackground(path:string,init:RequestInit){const created=await api<{id:string}>(path,init);activeJobId.value=created.id;for(;;){const job=await api<{status:string;progress:number;message:string;result?:unknown;error?:string}>(`/jobs/${created.id}`);jobProgress.value={value:job.progress,message:job.message};if(job.status==="completed"){activeJobId.value="";return job.result}if(job.status==="failed"){activeJobId.value="";throw new Error(job.error||"任务失败")}if(job.status==="cancelled"){activeJobId.value="";throw new Error("任务已取消")}await new Promise(resolve=>setTimeout(resolve,250))}}
async function cancelJob(){if(activeJobId.value)await api(`/jobs/${activeJobId.value}/cancel`,{method:"POST"})}
async function finishWizard(){if(!profile.value||!wizard.value)return;wizardRunning.value=true;try{const target=wizard.value;let success="操作完成";
  if(target.kind==="export"&&target.table){await download(`${API_BASE}/data/export?profile_id=${profile.value.id}&database=${encodeURIComponent(target.database)}&table=${encodeURIComponent(target.table)}&format=${wizardFormat.value}`,`${target.table}.${wizardFormat.value}`);success=`已导出 ${wizardFormat.value.toUpperCase()}`}
  else if(target.kind==="dump"){await download(`${API_BASE}/sql/dump?profile_id=${profile.value.id}&database=${encodeURIComponent(target.database)}&table=${encodeURIComponent(target.table||"")}&include_data=${wizardIncludeData.value}`,`${target.table||target.database}.sql`);success="SQL 转储已生成"}
  else if(target.kind==="generate"&&target.table){const result=await runBackground("/jobs/generate",{method:"POST",body:jsonBody({profile_id:profile.value.id,database:target.database,table:target.table,count:wizardCount.value})}) as {affected_rows?:number};success=`已生成 ${result?.affected_rows||wizardCount.value} 行数据`}
  else if((target.kind==="import"||target.kind==="sql")&&wizardFile.value){const form=new FormData();form.append("file",wizardFile.value);if(target.kind==="import"&&target.table){const result=await runBackground(`/jobs/import?profile_id=${profile.value.id}&database=${encodeURIComponent(target.database)}&table=${encodeURIComponent(target.table)}`,{method:"POST",body:form}) as {affected_rows?:number};success=`成功导入 ${result?.affected_rows||0} 行`}else{const result=await runBackground(`/jobs/sql-file?profile_id=${profile.value.id}&database=${encodeURIComponent(target.database)}`,{method:"POST",body:form}) as {statements?:number};success=`SQL 文件执行完成：${result?.statements||0} 条语句`}}
  await loadObjects(target.database);const dataTab=tabs.value.find(item=>item.type==="data"&&item.database===target.database&&item.table===target.table);if(dataTab?.type==="data")await loadData(dataTab);wizard.value=undefined;flash(success)
}catch(reason){flashError(reason)}finally{wizardRunning.value=false}}

async function testCurrentConnection() { if (!profile.value || !await checkConnection(true)) return; try { await api(`/connections/${profile.value.id}/test`, { method:"POST" }); connectionState.value="online"; flash("MySQL 连接正常"); } catch (reason) { connectionState.value="offline"; flashError(reason); } }
function toolbarItems(){return [{label:"连接",icon:"lucide:plug-zap",action:testCurrentConnection},{label:"新建数据库",icon:"lucide:database-backup",action:openCreateDatabase},{label:"新建查询",icon:"lucide:square-terminal",action:()=>newQuery()},{label:"新建表",icon:"lucide:table-properties",action:()=>openDesigner()},{label:"视图",icon:"lucide:panels-top-left",action:()=>newQuery(database.value,"CREATE OR REPLACE VIEW view_name AS\nSELECT 1 AS value;")},{label:"函数",icon:"lucide:function-square",action:()=>newQuery(database.value,"CREATE FUNCTION function_name() RETURNS INT DETERMINISTIC RETURN 1;")},{label:"触发器",icon:"lucide:zap",action:()=>newQuery(database.value,"CREATE TRIGGER trigger_name BEFORE INSERT ON table_name FOR EACH ROW SET NEW.created_at = NOW();")},{label:"事件",icon:"lucide:clock-3",action:()=>newQuery(database.value,"CREATE EVENT event_name ON SCHEDULE EVERY 1 DAY DO SELECT 1;")},{label:"用户权限",icon:"lucide:user-round-cog",action:()=>showPrivileges(database.value,"")},{label:"备份",icon:"lucide:archive-restore",action:()=>openWizard({kind:"dump",database:database.value})}]}
</script>

<template>
  <main v-if="!authReady" class="loading-screen"><div class="brand-logo">D</div><span>正在恢复工作区…</span></main>
  <main v-else-if="!user" class="login-screen"><form class="login-card" @submit.prevent="login"><div class="brand-logo large">D</div><h1>DeeBee</h1><p>MySQL 数据库工作台 · Vue</p><label>用户名<input v-model="loginUser" aria-label="用户名" autocomplete="username" /></label><label>密码<input v-model="loginPassword" aria-label="密码" type="password" autocomplete="current-password" /></label><div v-if="loginError" class="form-error">{{ loginError }}</div><button class="primary login-button" :disabled="loginLoading">{{ loginLoading ? "正在登录…" : "登录工作台" }}</button></form></main>
  <main v-else-if="fatal" class="fatal"><section><Icon icon="lucide:circle-alert" /><h2>无法打开工作台</h2><p>{{ fatal }}</p><button @click="fatal='';bootstrap()">重试</button><button @click="logout">退出登录</button></section></main>
  <main v-else class="app-shell">
    <section class="toolbar" aria-label="数据库工具栏"><button v-for="item in toolbarItems()" :key="item.label" @click="item.action"><Icon :icon="item.icon" /><span>{{ item.label }}</span></button><div class="toolbar-divider" /><button v-if="active?.type==='query'" @click="runQuery(active)"><Icon icon="lucide:play" class="green" /><span>运行</span></button><button v-if="active?.type==='query'" @click="cancelQuery(active)"><Icon icon="lucide:square" /><span>停止</span></button><button v-if="active?.type==='query'" @click="transaction(active,'commit')"><Icon icon="lucide:git-commit-horizontal" /><span>提交</span></button><button v-if="active?.type==='query'" @click="transaction(active,'rollback')"><Icon icon="lucide:undo-2" /><span>回滚</span></button><span class="toolbar-spacer" /><button class="connection-state" :class="connectionState" :title="connectionState==='online'?'连接正常；点击检测连接':'点击立即重新连接'" @click="checkConnection(true)"><i /><span>{{ profile?.name }} · MySQL · {{ profile?.user }}</span><b>{{ connectionLabel }}</b></button><button class="avatar" title="退出登录" @click="logout">{{ user.slice(0,2).toUpperCase() }}</button></section>
    <section class="workspace">
      <aside class="explorer"><header><strong>连接</strong><button aria-label="刷新服务器" @click="refreshServer"><Icon icon="lucide:refresh-cw" /></button></header><label class="tree-search"><Icon icon="lucide:search" /><input v-model="treeFilter" aria-label="筛选数据库对象" placeholder="筛选数据库或对象" /></label><DatabaseTree v-if="profile" :profile="profile" :server-expanded="serverExpanded" :databases="databases" :selected="database" :expanded="expanded" :objects="objects" :filter="treeFilter" @toggle-server="serverExpanded=!serverExpanded" @server-menu="serverMenu" @select-database="chooseDatabase" @toggle-database="toggleDatabase" @open-table="openData" @design-table="openDesigner" @open-list="openList" @open-object="openObject" @database-menu="databaseMenu" @table-menu="tableMenu" @object-menu="objectMenu" @inspect="inspect" /><footer><span>{{ databases.length }} 个数据库</span><span :class="`connection-${connectionState}`">{{ connectionLabel }}</span></footer></aside>
      <section class="content">
        <nav class="tabs" role="tablist"><div v-for="tab in tabs" :key="tab.id" class="tab" :class="{ current: activeId===tab.id }" role="tab" tabindex="0" :aria-selected="activeId===tab.id" @click="selectTab(tab)" @keydown.enter.prevent="selectTab(tab)" @keydown.space.prevent="selectTab(tab)" @contextmenu.prevent="tabMenu($event,tab)"><Icon :icon="tab.type==='query'?'lucide:square-terminal':tab.type==='data'?'lucide:table-2':tab.type==='designer'?'lucide:panel-top-open':'lucide:folder-tree'" /><span>{{ tab.title }}</span><i v-if="tab.type==='query'&&tab.sql">●</i><button :aria-label="`关闭 ${tab.title}`" @click.stop="closeTab(tab)"><Icon icon="lucide:x" /></button></div><button class="add-tab" aria-label="新建查询标签" @click="newQuery()"><Icon icon="lucide:plus" /></button></nav>
        <section v-if="!active" class="empty-workspace"><Icon icon="lucide:database-zap" /><h2>开始使用 DeeBee</h2><p>运行 SQL、浏览数据或维护表结构。</p><div><button class="primary" @click="newQuery()">新建查询</button><button @click="openDesigner()">新建表</button></div></section>
        <section v-else-if="active.type==='query'" ref="queryViewRef" class="view query-view">
          <div class="query-bar"><button class="run-button" :disabled="active.loading" @click="runQuery(active)"><Icon icon="lucide:play" />运行</button><button :disabled="!active.loading" @click="cancelQuery(active)"><Icon icon="lucide:square" />停止</button><button @click="editorRef?.formatSql()"><Icon icon="lucide:wand-sparkles" />格式化</button><button @click="runQuery(active,`EXPLAIN ${active.sql}`)"><Icon icon="lucide:workflow" />执行计划</button><span class="bar-divider" /><button @click="transaction(active,'commit')">提交</button><button @click="transaction(active,'rollback')">回滚</button><button class="autocommit" :class="{on:active.autocommit}" @click="toggleAutocommit(active)"><span /><b>自动提交</b></button><label class="database-switch"><Icon icon="lucide:database" />数据库<select :value="active.database" aria-label="查询数据库" @change="switchQueryDatabase(active,($event.target as HTMLSelectElement).value)"><option v-for="db in databases" :key="db.name" :value="db.name">{{ db.name }}</option></select></label><button @click="historyOpen=!historyOpen"><Icon icon="lucide:history" />历史</button></div>
          <div class="editor-wrap" :style="{height:`${queryEditorHeight}px`}"><SqlEditor ref="editorRef" v-model="active.sql" :catalog="catalogs[active.database]" @run="runQuery(active,$event)" /><aside v-if="historyOpen" class="history-panel"><header><strong>查询与历史</strong><button @click="historyOpen=false"><Icon icon="lucide:x" /></button></header><h4>已保存查询</h4><button v-for="item in savedQueries" :key="item.name" @click="useSavedQuery(item)"><b>{{ item.name }}</b><code>{{ item.sql }}</code></button><h4>最近执行</h4><button v-for="(sql,index) in history" :key="index" @click="active.sql=sql;historyOpen=false"><code>{{ sql }}</code></button></aside></div>
          <div class="query-splitter" role="separator" aria-label="调整 SQL 编辑区高度" aria-orientation="horizontal" :aria-valuemin="120" :aria-valuemax="editorHeightLimit()" :aria-valuenow="queryEditorHeight" tabindex="0" title="拖动调整 SQL 编辑区高度，双击恢复默认" @pointerdown="startEditorResize" @keydown="resizeEditorByKeyboard" @dblclick="setEditorHeight(260)"><span><i /><i /><i /></span></div>
          <nav class="result-tabs"><button :class="{current:resultPane==='message'}" @click="resultPane='message'">消息</button><button :class="{current:resultPane==='summary'}" @click="resultPane='summary'">摘要</button><template v-for="(result,index) in active.response?.results" :key="index"><button v-if="result.kind==='rows'" :class="{current:resultPane===`result-${index}`}" @click="resultPane=`result-${index}`">结果 {{ index+1 }} <span>{{ result.row_count }}</span></button></template><button :class="{current:resultPane==='profile'}" @click="resultPane='profile'">Profile</button><button :class="{current:resultPane==='status'}" @click="resultPane='status'">状态</button></nav>
          <div v-if="resultPane==='message'" class="query-message" :class="{error:active.error}"><Icon :icon="active.loading?'lucide:loader-circle':active.error?'lucide:circle-x':'lucide:circle-check'" :class="{spin:active.loading}" /><strong>{{ active.loading?'正在执行…':active.error?'执行失败':active.response?'执行完成':'准备就绪' }}</strong><pre v-if="active.error">{{ active.error }}</pre><p v-else-if="active.response">{{ active.response.results.length }} 个结果，耗时 {{ active.response.elapsed_ms }} ms</p><p v-else>SQL 编辑器支持当前数据库的表、视图、字段、别名、函数和 MySQL 关键字补全。</p></div>
          <div v-else-if="resultPane==='summary'" class="summary-pane"><div><b>{{ active.response?.elapsed_ms || 0 }} ms</b><span>执行时间</span></div><div><b>{{ active.response?.results.length || 0 }}</b><span>结果集</span></div><div><b>{{ active.response?.results.reduce((n,r)=>n+(r.row_count||r.affected_rows||0),0) || 0 }}</b><span>行数/影响行</span></div><div><b>{{ active.response?.warnings?.length || 0 }}</b><span>警告</span></div></div>
          <EditableGrid v-else-if="activeResult?.kind==='rows'" ref="resultGridRef" :columns="activeResult.columns || []" :rows="activeResult.rows || []" :storage-key="`query:${active.database}`" @menu="(event,row,column)=>resultMenu(event,row,column,activeResult!)" />
          <div v-else-if="resultPane==='profile'" class="query-message"><strong>执行概要</strong><pre>{{ JSON.stringify(active.response?.results,null,2) }}</pre></div><div v-else-if="resultPane==='status'" class="query-message"><strong>服务器状态</strong><pre>{{ JSON.stringify(active.response?.status || {},null,2) }}</pre></div>
          <footer class="statusbar"><span>{{ active.error?'查询失败':'就绪' }}</span><span>UTF-8 · MySQL · {{ active.database }}</span><span>{{ active.autocommit?'自动提交':'手动事务' }}</span></footer>
        </section>
        <section v-else-if="activeData" class="view data-view"><div class="data-toolbar"><button @click="rowDialog={mode:'insert',tabId:activeData.id,values:{}}"><Icon icon="lucide:plus" />添加记录</button><button :disabled="activeData.selected==null" class="danger-text" @click="deleteActiveRow"><Icon icon="lucide:trash-2" />删除</button><span class="separator" /><label>筛选<select v-model="activeData.filterColumn" aria-label="筛选字段"><option value="">选择字段</option><option v-for="column in activeData.data?.columns" :key="column.name">{{ column.name }}</option></select><input v-model="activeData.filterValue" aria-label="筛选值" placeholder="包含…" /><button @click="reloadActiveData({page:1})">应用</button></label><span class="grow" /><button @click="openDesigner(activeData.table,activeData.database)"><Icon icon="lucide:panel-top-open" />设计表</button><button @click="reloadActiveData()"><Icon icon="lucide:refresh-cw" />刷新</button><span class="separator" /><button @click="openWizard({kind:'import',database:activeData.database,table:activeData.table})"><Icon icon="lucide:file-input" />导入</button><button @click="openWizard({kind:'export',database:activeData.database,table:activeData.table})"><Icon icon="lucide:file-output" />导出</button></div><div v-if="activeData.error" class="inline-error">{{ activeData.error }}</div><EditableGrid ref="resultGridRef" :columns="activeData.data?.columns || []" :rows="activeData.data?.rows || []" :primary-key="activeData.data?.primary_key || []" :editable="true" :selected="activeData.selected" :storage-key="`${activeData.database}:${activeData.table}`" @select="activeData.selected=$event" @sort="sortActiveData" @save="saveActiveInline" @menu="(event,row,column)=>dataResultMenu(event,row,column,activeData?.data)" /><footer class="data-footer"><span>第 {{ activeData.page }} 页，共 {{ activeData.data?.total || 0 }} 行</span><div><button :disabled="activeData.page<=1" @click="reloadActiveData({page:activeData.page-1})"><Icon icon="lucide:chevron-left" /></button><b>{{ activeData.page }}</b><button :disabled="activeData.page*100 >= (activeData.data?.total||0)" @click="reloadActiveData({page:activeData.page+1})"><Icon icon="lucide:chevron-right" /></button></div><span>主键：{{ activeData.data?.primary_key.join(', ') || '无' }}</span></footer></section>
        <TableDesigner v-else-if="activeDesigner" :tab="activeDesigner" @update="updateSpec(activeDesigner,$event)" @pane="activeDesigner.pane=$event" @preview="previewDdl(activeDesigner)" @apply="applyDdl(activeDesigner)" />
        <ObjectList v-else-if="activeObjectsTab" :tab="activeObjectsTab" :objects="objects[activeObjectsTab.database]" @open-table="openData($event,activeObjectsTab.database)" @design-table="openDesigner($event,activeObjectsTab.database)" @menu="objectListMenu" />
      </section>
      <aside v-if="inspector" class="inspector"><header><strong>对象信息</strong><button @click="inspector=undefined"><Icon icon="lucide:x" /></button></header><div class="inspector-icon"><Icon icon="lucide:database" /></div><h3>{{ inspector.title }}</h3><p>{{ inspector.subtitle }}</p><dl><div v-for="(line,index) in inspector.lines" :key="index"><dt>{{ index+1 }}</dt><dd>{{ line }}</dd></div></dl></aside>
    </section>
    <ContextMenu :menu="contextMenu" @close="closeMenu" />
    <div v-if="notice" class="toast" :class="{error:noticeError}">{{ notice }}</div>
    <div v-if="createDatabaseDialog" class="modal-backdrop" @mousedown.self="createDatabaseDialog=undefined"><form class="modal create-database-modal" role="dialog" aria-label="新建数据库" @submit.prevent="createDatabase"><header><div><Icon icon="lucide:database-backup" /><span><strong>新建数据库</strong><small>{{ profile?.name }} · {{ profile?.host }}:{{ profile?.port }}</small></span></div><button type="button" aria-label="关闭新建数据库" @click="createDatabaseDialog=undefined"><Icon icon="lucide:x" /></button></header><section><div class="database-visual"><Icon icon="lucide:server" /><i /><Icon icon="lucide:database" /></div><label><span>数据库名称</span><input v-model.trim="createDatabaseDialog.name" aria-label="数据库名称" autofocus autocomplete="off" placeholder="例如 app_data" pattern="[A-Za-z_][A-Za-z0-9_$]*" required /></label><label><span>字符集</span><select v-model="createDatabaseDialog.charset" aria-label="数据库字符集"><option value="utf8mb4">utf8mb4</option><option value="utf8">utf8</option><option value="latin1">latin1</option><option value="ascii">ascii</option></select></label><label><span>排序规则</span><select v-model="createDatabaseDialog.collation" aria-label="数据库排序规则"><option value="utf8mb4_unicode_ci">utf8mb4_unicode_ci</option><option value="utf8mb4_general_ci">utf8mb4_general_ci</option><option value="utf8mb4_bin">utf8mb4_bin</option></select></label><p>数据库会创建在当前服务器上；名称仅支持字母、数字、下划线和 $。</p></section><footer><button type="button" @click="createDatabaseDialog=undefined">取消</button><button class="primary" :disabled="createDatabaseDialog.saving || !createDatabaseDialog.name">{{ createDatabaseDialog.saving ? '正在创建…' : '创建' }}</button></footer></form></div>
    <div v-if="rowDialog && activeData" class="modal-backdrop" @mousedown.self="rowDialog=undefined"><form class="modal row-modal" @submit.prevent="insertActiveRow"><header><div><Icon icon="lucide:plus" /><span><strong>添加记录</strong><small>{{ activeData.table }}</small></span></div><button type="button" @click="rowDialog=undefined"><Icon icon="lucide:x" /></button></header><section><label v-for="column in activeData.data?.columns" :key="column.name"><span><b>{{ column.name }}</b><small>{{ column.data_type }}{{ column.nullable?' · 可空':'' }}</small></span><input v-model="rowDialog.values[column.name]" :disabled="column.extra.includes('AUTO_INCREMENT')" :aria-label="`记录字段 ${column.name}`" /></label></section><footer><button type="button" @click="rowDialog=undefined">取消</button><button class="primary">保存</button></footer></form></div>
    <div v-if="wizard" class="modal-backdrop"><section class="modal operation-wizard" role="dialog" :aria-label="({import:'数据导入向导',export:'数据导出向导',generate:'测试数据生成器',dump:'SQL 转储向导',sql:'执行 SQL 文件'} as const)[wizard.kind]"><header><div><Icon icon="lucide:wand-sparkles" /><span><strong>{{ ({import:'数据导入向导',export:'数据导出向导',generate:'测试数据生成器',dump:'SQL 转储向导',sql:'执行 SQL 文件'} as const)[wizard.kind] }}</strong><small>{{ wizard.database }}{{ wizard.table?` · ${wizard.table}`:'' }}</small></span></div><button @click="wizard=undefined"><Icon icon="lucide:x" /></button></header><div class="wizard-steps"><span :class="{current:wizardStep===1,done:wizardStep===2}">1 配置</span><i /><span :class="{current:wizardStep===2}">2 确认执行</span></div><div class="wizard-body"><template v-if="wizardStep===1"><label v-if="wizard.kind==='import'||wizard.kind==='sql'" class="file-drop"><input type="file" :accept="wizard.kind==='sql'?'.sql,.txt':'.csv,.json,.xlsx'" @change="wizardFile=($event.target as HTMLInputElement).files?.[0]" /><Icon icon="lucide:file-up" /><b>{{ wizardFile?.name || '选择文件' }}</b><span>支持 {{ wizard.kind==='sql'?'SQL/TXT':'CSV/JSON/XLSX' }}</span></label><div v-if="wizard.kind==='export'" class="wizard-fields"><label>文件格式<select v-model="wizardFormat" aria-label="文件格式"><option value="csv">CSV</option><option value="xlsx">Excel XLSX</option><option value="json">JSON</option><option value="sql">SQL INSERT</option></select></label></div><div v-if="wizard.kind==='dump'" class="wizard-fields"><label><input v-model="wizardIncludeData" type="checkbox" />包含表数据</label></div><div v-if="wizard.kind==='generate'" class="wizard-fields"><label>生成行数<input v-model.number="wizardCount" aria-label="生成行数" type="number" min="1" max="10000" /></label></div></template><div v-else class="wizard-summary"><strong>操作确认</strong><dl><div><dt>目标</dt><dd>{{ wizard.database }}{{ wizard.table?`.${wizard.table}`:'' }}</dd></div><div v-if="wizardFile"><dt>文件</dt><dd>{{ wizardFile.name }}</dd></div><div v-if="wizard.kind==='generate'"><dt>记录</dt><dd>{{ wizardCount }} 行</dd></div></dl><div v-if="wizardRunning" class="wizard-progress"><i :style="{width:`${Math.max(4,jobProgress.value)}%`}" /></div><p v-if="wizardRunning">{{ jobProgress.message || '正在执行…' }} · {{ jobProgress.value }}%</p></div></div><footer><button @click="wizardRunning?cancelJob():(wizard=undefined)">{{ wizardRunning?'取消任务':'取消' }}</button><button v-if="wizardStep===2" :disabled="wizardRunning" @click="wizardStep=1">上一步</button><button v-if="wizardStep===1" class="primary" :disabled="(wizard.kind==='import'||wizard.kind==='sql')&&!wizardFile" @click="wizardStep=2">下一步</button><button v-else class="primary" :disabled="wizardRunning" @click="finishWizard">{{ wizardRunning?'后台执行中…':'开始执行' }}</button></footer></section></div>
    <div v-if="searchDialog" class="modal-backdrop" @mousedown.self="searchDialog=undefined"><section class="modal search-modal"><header><div><Icon icon="lucide:search" /><span><strong>在数据库中查找</strong><small>“{{ searchDialog.term }}”</small></span></div><button @click="searchDialog=undefined"><Icon icon="lucide:x" /></button></header><div class="search-results"><button v-for="(row,index) in searchDialog.rows" :key="index" @dblclick="newQuery(database,`SELECT * FROM \`${row.name}\` LIMIT 100;`);searchDialog=undefined"><Icon :icon="row.kind==='table'?'lucide:table-2':'lucide:columns-3'" /><span><b>{{ row.name }}</b><small>{{ row.kind }} · {{ row.detail }}</small></span></button></div><footer><span>{{ searchDialog.rows.length }} 个结果</span><button @click="searchDialog=undefined">关闭</button></footer></section></div>
  </main>
</template>
